# Analyzing Key Operational Metrics in the Airline Industry

In [26]:
import pandas as pd
import numpy as np

# Load the dataset
# Replace 'flight_delay_cancellation.csv' with the actual path of the dataset if downloaded locally
data = pd.read_csv('flights_sample_3m.csv')

# Display initial rows to understand structure
print("Initial Data Preview:\n", data.head())

Initial Data Preview:
       FL_DATE                AIRLINE                AIRLINE_DOT AIRLINE_CODE  \
0  2019-01-09  United Air Lines Inc.  United Air Lines Inc.: UA           UA
1  2022-11-19   Delta Air Lines Inc.   Delta Air Lines Inc.: DL           DL
2  2022-07-22  United Air Lines Inc.  United Air Lines Inc.: UA           UA
3  2023-03-06   Delta Air Lines Inc.   Delta Air Lines Inc.: DL           DL
4  2020-02-23       Spirit Air Lines       Spirit Air Lines: NK           NK

   DOT_CODE  FL_NUMBER ORIGIN          ORIGIN_CITY DEST  \
0     19977       1562    FLL  Fort Lauderdale, FL  EWR
1     19790       1149    MSP      Minneapolis, MN  SEA
2     19977        459    DEN           Denver, CO  MSP
3     19790       2295    MSP      Minneapolis, MN  SFO
4     20416        407    MCO          Orlando, FL  DFW

               DEST_CITY  ...  DIVERTED  CRS_ELAPSED_TIME  ELAPSED_TIME  \
0             Newark, NJ  ...       0.0             186.0         176.0
1            Seattle, WA  ...       0.0             235.0         236.0
2        Minneapolis, MN  ...       0.0             118.0         112.0
3      San Francisco, CA  ...       0.0             260.0         285.0
4  Dallas/Fort Worth, TX  ...       0.0             181.0         182.0

   AIR_TIME  DISTANCE  DELAY_DUE_CARRIER  DELAY_DUE_WEATHER  DELAY_DUE_NAS  \
0     153.0    1065.0                NaN                NaN            NaN
1     189.0    1399.0                NaN                NaN            NaN
2      87.0     680.0                NaN                NaN            NaN
3     249.0    1589.0                0.0                0.0           24.0
4     153.0     985.0                NaN                NaN            NaN

   DELAY_DUE_SECURITY  DELAY_DUE_LATE_AIRCRAFT
0                 NaN                      NaN
1                 NaN                      NaN
2                 NaN                      NaN
3                 0.0                      0.0
4                 NaN                      NaN

[5 rows x 32 columns]

In [30]:
data.describe()

,DOT_CODE,FL_NUMBER,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,...,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
count,3.000000e+06,3.000000e+06,3.000000e+06,2.922385e+06,2.922356e+06,2.921194e+06,2.921194e+06,2.920056e+06,2.920056e+06,3.000000e+06,...,3.000000e+06,2.999986e+06,2.913802e+06,2.913802e+06,3.000000e+06,533863.000000,533863.000000,533863.000000,533863.000000,533863.000000
mean,1.997629e+04,2.511536e+03,1.327062e+03,1.329776e+03,1.012333e+01,1.664305e+01,1.352361e+03,1.462500e+03,7.678982e+00,1.490561e+03,...,2.352000e-03,1.422758e+02,1.366205e+02,1.123108e+02,8.093616e+02,24.759086,3.985260,13.164728,0.145931,25.471282
std,3.772846e+02,1.747258e+03,4.858789e+02,4.993101e+02,4.925183e+01,9.192901e+00,5.008727e+02,5.272368e+02,6.269639e+00,5.115476e+02,...,4.844036e-02,7.155669e+01,7.167582e+01,6.975484e+01,5.878939e+02,71.771845,32.410796,33.161122,3.582053,55.766892
min,1.939300e+04,1.000000e+00,1.000000e+00,1.000000e+00,-9.000000e+01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,0.000000e+00,1.000000e+00,1.500000e+01,8.000000e+00,2.900000e+01,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.979000e+04,1.051000e+03,9.150000e+02,9.160000e+02,-6.000000e+00,1.100000e+01,9.310000e+02,1.049000e+03,4.000000e+00,1.107000e+03,...,0.000000e+00,9.000000e+01,8.400000e+01,6.100000e+01,3.770000e+02,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.993000e+04,2.152000e+03,1.320000e+03,1.323000e+03,-2.000000e+00,1.400000e+01,1.336000e+03,1.501000e+03,6.000000e+00,1.516000e+03,...,0.000000e+00,1.250000e+02,1.200000e+02,9.500000e+01,6.510000e+02,4.000000,0.000000,0.000000,0.000000,0.000000
75%,2.036800e+04,3.797000e+03,1.730000e+03,1.739000e+03,6.000000e+00,1.900000e+01,1.752000e+03,1.908000e+03,9.000000e+00,1.919000e+03,...,0.000000e+00,1.720000e+02,1.670000e+02,1.420000e+02,1.046000e+03,23.000000,0.000000,17.000000,0.000000,30.000000
max,2.045200e+04,9.562000e+03,2.359000e+03,2.400000e+03,2.966000e+03,1.840000e+02,2.400000e+03,2.400000e+03,2.490000e+02,2.400000e+03,...,1.000000e+00,7.050000e+02,7.390000e+02,6.920000e+02,5.812000e+03,2934.000000,1653.000000,1741.000000,1185.000000,2557.000000

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Data columns (total 32 columns):
 #   Column                   Dtype
---  ------                   -----
 0   FL_DATE                  object
 1   AIRLINE                  object
 2   AIRLINE_DOT              object
 3   AIRLINE_CODE             object
 4   DOT_CODE                 int64
 5   FL_NUMBER                int64
 6   ORIGIN                   object
 7   ORIGIN_CITY              object
 8   DEST                     object
 9   DEST_CITY                object
 10  CRS_DEP_TIME             int64
 11  DEP_TIME                 float64
 12  DEP_DELAY                float64
 13  TAXI_OUT                 float64
 14  WHEELS_OFF               float64
 15  WHEELS_ON                float64
 16  TAXI_IN                  float64
 17  CRS_ARR_TIME             int64
 18  ARR_TIME                 float64
 19  ARR_DELAY                float64
 20  CANCELLED                float64
 21  CANCELLATION_CODE        object
 22  DIVERTED                 float64
 23  CRS_ELAPSED_TIME         float64
 24  ELAPSED_TIME             float64
 25  AIR_TIME                 float64
 26  DISTANCE                 float64
 27  DELAY_DUE_CARRIER        float64
 28  DELAY_DUE_WEATHER        float64
 29  DELAY_DUE_NAS            float64
 30  DELAY_DUE_SECURITY       float64
 31  DELAY_DUE_LATE_AIRCRAFT  float64
dtypes: float64(19), int64(4), object(9)
memory usage: 732.4+ MB

In [32]:

# Select relevant columns for analysis
columns_of_interest = ['FL_DATE', 'AIRLINE', 'DEP_DELAY', 'ARR_DELAY', 'CANCELLED', 'CANCELLATION_CODE', 'DISTANCE']
data = data[columns_of_interest]

# Display data information to understand data types and missing values
print("\nData Information:\n")
data.info()

Data Information:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Data columns (total 7 columns):
 #   Column             Dtype
---  ------             -----
 0   FL_DATE            object
 1   AIRLINE            object
 2   DEP_DELAY          float64
 3   ARR_DELAY          float64
 4   CANCELLED          float64
 5   CANCELLATION_CODE  object
 6   DISTANCE           float64
dtypes: float64(4), object(3)
memory usage: 160.2+ MB

In [34]:

# Check for missing values in selected columns
missing_values = data.isnull().sum()
print("\nMissing Values:\n", missing_values)

Missing Values:
 FL_DATE                    0
AIRLINE                    0
DEP_DELAY              77644
ARR_DELAY              86198
CANCELLED                  0
CANCELLATION_CODE    2920860
DISTANCE                   0
dtype: int64

In [36]:

# Drop rows with missing values in critical columns for delay analysis
data = data.dropna(subset=['DEP_DELAY', 'ARR_DELAY', 'DISTANCE'])

# Convert 'CANCELLED' to boolean type and 'CANCELLATION_CODE' to categorical
data['CANCELLED'] = data['CANCELLED'].astype(bool)
data['CANCELLATION_CODE'] = data['CANCELLATION_CODE'].astype('category')

# Normalize 'DISTANCE' and 'DEP_DELAY' for analysis
data['normalized_distance'] = (data['DISTANCE'] - data['DISTANCE'].mean()) / data['DISTANCE'].std()
data['normalized_dep_delay'] = (data['DEP_DELAY'] - data['DEP_DELAY'].mean()) / data['DEP_DELAY'].std()

# Outlier detection in departure delays (e.g., Z-score method)
z_scores = np.abs((data['DEP_DELAY'] - data['DEP_DELAY'].mean()) / data['DEP_DELAY'].std())
outliers = data[z_scores > 3]  # Rows where Z-score > 3 considered as outliers
print("\nOutliers in Departure Delays:\n", outliers)

Outliers in Departure Delays:
             FL_DATE                 AIRLINE  DEP_DELAY  ARR_DELAY  CANCELLED  \
29       2023-04-15        Republic Airline     1069.0     1124.0      False
115      2023-01-30        Spirit Air Lines      223.0      280.0      False
188      2019-12-01  Southwest Airlines Co.      333.0      340.0      False
463      2022-07-18   SkyWest Airlines Inc.      238.0      232.0      False
506      2019-03-15       Endeavor Air Inc.      225.0      250.0      False
...             ...                     ...        ...        ...        ...
2999622  2019-07-19    Delta Air Lines Inc.      236.0      226.0      False
2999699  2022-07-30   SkyWest Airlines Inc.      691.0      703.0      False
2999897  2019-07-13   United Air Lines Inc.      192.0      200.0      False
2999978  2019-11-11        Spirit Air Lines      201.0      311.0      False
2999988  2019-04-16   SkyWest Airlines Inc.      224.0      214.0      False

        CANCELLATION_CODE  DISTANCE  normalized_distance  normalized_dep_delay
29                    NaN    1008.0             0.334731             21.589246
115                   NaN    1235.0             0.719887              4.341497
188                   NaN    2026.0             2.061998              6.584112
463                   NaN     349.0            -0.783412              4.647308
506                   NaN     585.0            -0.382984              4.382272
...                   ...       ...                  ...                   ...
2999622               NaN     526.0            -0.483091              4.606533
2999699               NaN     598.0            -0.360927             13.882805
2999897               NaN    1744.0             1.583521              3.709487
2999978               NaN     594.0            -0.367714              3.892974
2999988               NaN     733.0            -0.131869              4.361884

[42845 rows x 9 columns]

In [38]:

# Final prepared dataset ready for analysis
print("\nPrepared Data Sample:\n", data.head())

Prepared Data Sample:
       FL_DATE                AIRLINE  DEP_DELAY  ARR_DELAY  CANCELLED  \
0  2019-01-09  United Air Lines Inc.       -4.0      -14.0      False
1  2022-11-19   Delta Air Lines Inc.       -6.0       -5.0      False
2  2022-07-22  United Air Lines Inc.        6.0        0.0      False
3  2023-03-06   Delta Air Lines Inc.       -1.0       24.0      False
4  2020-02-23       Spirit Air Lines       -2.0       -1.0      False

  CANCELLATION_CODE  DISTANCE  normalized_distance  normalized_dep_delay
0               NaN    1065.0             0.431444             -0.286445
1               NaN    1399.0             0.998151             -0.327220
2               NaN     680.0            -0.221795             -0.082571
3               NaN    1589.0             1.320529             -0.225283
4               NaN     985.0             0.295706             -0.245670